version: '3.1'
services:
  teamspeak:
    build:
      context: .
      args:
        TS_UID: $TS_UID
        TS_GID: $TS_GID
    restart: always
    volumes:
      - /host/data/dir:/var/ts3server
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
